services:
  mysql:
    container_name: "mysql-dev"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "vote"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
    ports:
      - "3306:3306"
